name: Activate Sports Cron Job

on:
  schedule:
    - cron: '30 17 * * 0' # Runs every Sunday at 5:30 PM UTC (Sunday 11:00 PM IST) — Activates sports for Monday
  workflow_dispatch: # Enables manual trigger

jobs:
  activate-sports:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Stops the job after 10 minutes if it doesn't complete
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Call Activate Sports API with Retry Logic
        env:
          SECRET_KEY: ${{ secrets.BACKUP_CRON_SECRET }}
          API_URL: ${{ secrets.ACTIVATE_SPORTS_API_URL }}
        run: |
          for i in {1..3}; do
            response=$(curl -X POST -s -w "%{http_code}" -o response_body.txt "$API_URL?secret=$SECRET_KEY")
            echo "Attempt $i: API Response Code: $response"
            echo "API Response Body:"
            cat response_body.txt
            if [ "$response" -eq 200 ]; then
              echo "Sports activation succeeded! Monday sports are now ON."
              break
            else
              echo "Sports activation failed. Retrying in 10 seconds..."
              sleep 10
            fi
          done

          if [ "$response" -ne 200 ]; then
            echo "Sports activation failed after 3 attempts. Exiting with error."
            exit 1
          fi
