name: Reset Bookings Cron Job

on:
  schedule:
    - cron: '0 18 * * *' # Runs every day at 12 AM Asia/Kolkata (UTC+5:30 is 18:00 UTC)

jobs:
  reset-bookings:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Call Reset Bookings API
        env:
          SECRET_KEY: ${{ secrets.BACKUP_CRON_SECRET }} # Use GitHub Secrets for your secret key
        run: |
          curl -X POST "https://courtside-xi.vercel.app/api/reset-bookings?secret=$SECRET_KEY"